language: rust
script: cargo test --features "serde rustc-serialize"

matrix:
  include:
    - os: linux
      rust: stable
      cache: cargo
    - os: linux
      rust: beta
      cache: cargo
    - os: linux
      rust: nightly
      cache: cargo
  allow_failures:
    - rust: beta
    - rust: nightly

notifications:
  email:
    on_success: never
