[package]
authors = ["Josh Holmer <jholmer.in@gmail.com>"]
description = "An entropy-based password strength estimator, originally for Javascript by Dropbox."
documentation = "https://docs.rs/zxcvbn"
homepage = "https://github.com/shssoichiro/zxcvbn-rs"
license = "MIT"
name = "zxcvbn"
repository = "https://github.com/shssoichiro/zxcvbn-rs"
version = "0.2.1"

[dependencies]
derive_builder = "0.2.1"
itertools = "0.5.8"
lazy_static = "0.2.2"
macro-attr = "0.2.0"
regex = "0.2.0"
time = "0.1.35"

[dependencies.clippy]
optional = true
version = ">=0.0.100"

[dependencies.onig]
features = ["static-libonig"]
version = "1.2.0"

[dependencies.rustc-serialize]
optional = true
version = "0.3"

[dependencies.serde]
optional = true
version = "<0.9"

[dev-dependencies]
quickcheck = "0.4.1"
serde_json = "0.8.4"

[features]
default = []
dev = ["clippy", "unstable", "rustc-serialize", "serde"]
unstable = ["regex/simd-accel", "lazy_static/nightly"]
